# Generated by Django 6.0.2 on 2026-02-16 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
