# Generated by Django 6.0.2 on 2026-02-16 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='quantity_used',
            new_name='used_quantity',
        ),
    ]
