# Generated by Django 6.0.2 on 2026-02-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_quantity_used_recipeingredient_used_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storageitem',
            name='unity',
        ),
        migrations.AlterField(
            model_name='storageitem',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
