# Generated by Django 6.0.2 on 2026-02-16 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_remove_storageitem_unity_alter_storageitem_quantity'),
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.storageitem'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='items',
            field=models.ManyToManyField(related_name='recipes', through='recipes.RecipeIngredient', to='storage.storageitem'),
        ),
        migrations.DeleteModel(
            name='StorageItem',
        ),
    ]
