# Generated by Django 6.0.2 on 2026-02-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageitem',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
